import { test, expect } from '@playwright/test';
import path from 'path';

const indexPath = path.join(__dirname, '../index.html');
const fileUrl = `file://${indexPath}`;

test.describe('UI Verification', () => {
    test('1. Verify Button Text', async ({ page }) => {
        await page.goto(fileUrl);
        const btn = page.locator('#nav-overview');
        await expect(btn).toHaveText('全景 & 旬 (Overview & Xun)');
    });

    test('2. Verify Grid Cell Expansion', async ({ page }) => {
        await page.goto(fileUrl);
        
        // Ensure we are in Detail View using the exposed helper
        await page.evaluate(() => {
            if (window.showXunDetail) {
                window.showXunDetail(0);
            }
        });

        // Wait for grid to render
        await page.waitForSelector('#detail-calendars-container .group', { timeout: 5000 });

        // Get initial height of a cell
        const cell = page.locator('#detail-calendars-container .group').first();
        const initialBox = await cell.boundingBox();
        
        // Inject long content to test expansion
        await page.evaluate(() => {
            const cells = document.querySelectorAll('#detail-calendars-container .group');
            if (cells.length > 0) {
                const cell = cells[0];
                const container = document.createElement('div');
                for(let i=0; i<50; i++) { // More content to ensure expansion
                    const span = document.createElement('span');
                    span.innerText = 'TestKeyword_' + i + ' '; // Add space for wrapping
                    span.className = 'text-xs p-1 m-1 bg-red-200 inline-block';
                    container.appendChild(span);
                }
                cell.appendChild(container);
            }
        });

        await page.waitForTimeout(500); // Allow render update
        const newBox = await cell.boundingBox();
        
        console.log(`Initial Height: ${initialBox?.height}, New Height: ${newBox?.height}`);
        expect(newBox?.height).toBeGreaterThan(initialBox?.height || 0);
    });

    test('3. Verify Mobile Scroll Interactions', async ({ page }) => {
        // Set mobile viewport
        await page.setViewportSize({ width: 375, height: 667 });
        await page.goto(fileUrl);
        
        // Ensure Macro View is active
        await page.evaluate(() => {
            window.showView('macro');
        });

        // Generate enough content to scroll
        await page.evaluate(() => {
            const container = document.getElementById('macro-list');
            for(let i=0; i<20; i++) {
                const div = document.createElement('div');
                div.style.height = '100px';
                div.textContent = 'Spacer ' + i;
                container.appendChild(div);
            }
        });

        // Scroll down > 300px
        await page.evaluate(() => window.scrollTo(0, 500));
        await page.waitForTimeout(1000); // Wait for transition

        const backToTopContainer = page.locator('#macro-back-to-top-container');
        const backToTopBtn = page.locator('#macro-back-to-top');
        
        // Check Back to Top is now visible (opacity-0 removed)
        await expect(backToTopContainer).not.toHaveClass(/opacity-0/);

        // Debug: Get Bounding Box
        const box = await backToTopBtn.boundingBox();
        console.log('Back to Top Button Box:', box);

        // Click Back to Top (force: true because sometimes overlays/animations interfere)
        await backToTopBtn.click({ force: true });
        await page.waitForTimeout(1000); // Wait for scroll

        // Verify scrolled back to top
        const scrollY = await page.evaluate(() => window.scrollY);
        expect(scrollY).toBeLessThan(10);
    });

    test('4. Verify Quick Scroll Down', async ({ page }) => {
        // Set mobile viewport
        await page.setViewportSize({ width: 375, height: 667 });
        await page.goto(fileUrl);
        
        // Ensure Macro View
        await page.evaluate(() => window.showView('macro'));

        // Generate content (Xun rows)
        // The page already has xun rows generated by init().
        // We need to ensure they are tall enough to scroll.
        // By default, they might be small.
        // Let's force them to be tall.
        await page.evaluate(() => {
            const rows = document.querySelectorAll('[id^="xun-row-"]');
            rows.forEach(row => row.style.height = '300px'); // Make each row 300px tall
        });

        // Scroll to top
        await page.evaluate(() => window.scrollTo(0, 0));
        await page.waitForTimeout(500);

        const scrollDownBtn = page.locator('#macro-scroll-down');
        
        // Click Scroll Down
        await scrollDownBtn.click({ force: true });
        await page.waitForTimeout(1000); // Wait for smooth scroll

        // Should have scrolled down.
        // First row is at 0. Height 300.
        // Second row starts at 300.
        // Scroll logic: finds first row with top > viewportHeight * 0.6
        // Viewport 667. 0.6 * 667 = 400.
        // Row 0 top=0. Not > 400.
        // Row 1 top=300. Not > 400.
        // Row 2 top=600. Yes > 400.
        // So it should scroll to Row 2 (index 2).
        
        const scrollY = await page.evaluate(() => window.scrollY);
        console.log('Scroll Y after click:', scrollY);
        expect(scrollY).toBeGreaterThan(100);
    });

    test('5. Verify Goal Alignment Fields Save & Restore', async ({ page }) => {
        await page.goto(fileUrl);
        await page.evaluate(() => localStorage.clear());
        await page.reload();
        await page.waitForSelector('#macro-list');

        await page.evaluate(() => {
            if (window.openModal) window.openModal('2026-01-01');
        });

        await expect(page.locator('#modal')).toHaveClass(/flex/);

        await page.locator('#xun-goal-input').fill('Test Goal');
        await page.locator('#xun-goal-input').blur();

        await page.locator('#xun-indicator-1').fill('Deep Work 45m');
        await page.locator('#xun-indicator-2').fill('Run 2km');
        await page.locator('#xun-indicator-3').fill('');
        await page.locator('#day-indicator-check-1').check();
        await page.locator('#day-indicator-check-2').check();

        await page.locator('#goal-checkin-input').check();
        await page.locator('#goal-confidence-input').fill('80');
        await page.locator('#goal-actions-input').fill('Write 300 words, Run 2km, Deep Work 45m');
        await page.locator('#goal-blockers-input').fill('Too tired');

        await page.locator('#modal-save').click();
        await expect(page.locator('#modal')).toHaveClass(/hidden/);

        const stored = await page.evaluate(() => ({
            userData: JSON.parse(localStorage.getItem('xun_calendar_data_v2') || '{}'),
            macroGoals: JSON.parse(localStorage.getItem('xun_macro_goals') || '{}')
        }));

        expect(stored.userData['2026-01-01'].goal_checkin).toBe(true);
        expect(stored.userData['2026-01-01'].goal_confidence).toBe(80);
        expect(stored.userData['2026-01-01'].goal_actions).toEqual(['Write 300 words', 'Run 2km', 'Deep Work 45m']);
        expect(stored.userData['2026-01-01'].goal_blockers).toBe('Too tired');
        expect(stored.userData['2026-01-01'].indicator_checkins).toEqual([true, true, false]);
        expect(stored.macroGoals['1'].goal).toBe('Test Goal');
        expect(stored.macroGoals['1'].indicators).toEqual(['Deep Work 45m', 'Run 2km']);

        await page.evaluate(() => {
            if (window.openModal) window.openModal('2026-01-01');
        });
        await expect(page.locator('#modal')).toHaveClass(/flex/);
        await expect(page.locator('#goal-checkin-input')).toBeChecked();
        await expect(page.locator('#goal-confidence-input')).toHaveValue('80');
        await expect(page.locator('#goal-actions-input')).toHaveValue('Write 300 words, Run 2km, Deep Work 45m');
        await expect(page.locator('#goal-blockers-input')).toHaveValue('Too tired');
        await expect(page.locator('#xun-indicator-1')).toHaveValue('Deep Work 45m');
        await expect(page.locator('#xun-indicator-2')).toHaveValue('Run 2km');
        await expect(page.locator('#xun-indicator-3')).toHaveValue('');
        await expect(page.locator('#day-indicator-check-1')).toBeChecked();
        await expect(page.locator('#day-indicator-check-2')).toBeChecked();
        await expect(page.locator('#day-indicator-check-3')).toBeDisabled();
    });
});

test.describe('Timezone Regression', () => {
    test.use({ timezoneId: 'Asia/Shanghai' });

    test('6. Verify Today Cell Is Editable In Macro Check-ins', async ({ page }) => {
        await page.addInitScript(() => {
            const fixedNow = new Date('2026-02-03T12:00:00');
            const RealDate = Date;
            class MockDate extends RealDate {
                constructor(...args: any[]) {
                    if (args.length === 0) {
                        super(fixedNow.getTime());
                        return;
                    }
                    super(...args);
                }
                static now() {
                    return fixedNow.getTime();
                }
            }
            (MockDate as any).parse = (RealDate as any).parse;
            (MockDate as any).UTC = (RealDate as any).UTC;
            (window as any).Date = MockDate as any;
        });

        await page.goto(fileUrl);
        await page.waitForSelector('#macro-list');

        const todayDot = page.locator('#xun-row-4 [title^="2026-02-03"]').first();
        await expect(todayDot).toHaveCount(1);
        await expect(todayDot).not.toHaveClass(/cursor-not-allowed/);

        await todayDot.click();
        await expect(todayDot).toHaveAttribute('title', /2026-02-03: 已打卡/);
    });
});
